# https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
# https://hub.docker.com/r/tensorflow/tensorflow/
tensorflow:
    image: registry.kuick.cn/cc/tensorflow:1.0
    container_name: tensorflow
    hostname: tensorflow
#    environment:
    volumes:
      - ../train:/notebooks/train
      - ../tensorflow-source/tensorflow/examples:/notebooks/example
#      - ../config/:/.jupyter/

    ports:
      - 8888:8888
    restart: always

